# Site settings

# Theme settings
title: Paris Ruby Workshop
description: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-merlot
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
